version: "3"
services:
  nginx:
    image: nginx
    links:
      - slackerboard
      - rails_server
      - socket_io
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/letsencrypt/www:/var/www
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - 80:80
      - 4200:4200
      - 8080:8080

  slackerboard:
    build: slackerboard
    command: yarn run dev
    volumes:
      - ./slackerboard:/usr/src/app
      - slackerboard_node_modules:/usr/src/app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=8080

  rails_server:
    build: rails_server
    command: bundle exec rails s -p 5000 -b 0.0.0.0
    environment:
      - PORT=5000
    env_file:
      - ./rails_server/.env
    volumes:
      - ./rails_server:/home/app/webapp
      - bundle:/usr/local/bundle
    links:
      - postgres
      - redis

  sidekiq:
    build: rails_server
    command: sidekiq -C config/sidekiq.yml
    env_file:
      - ./rails_server/.env
    volumes:
      - ./rails_server:/home/app/webapp
      - bundle:/usr/local/bundle
    links:
      - postgres
      - redis

  socket_io:
    build: socket_io
    command: npm start
    links:
      - redis
    volumes:
      - ./socket_io:/usr/src/app
      - socket_io_node_modules:/usr/src/app/node_modules

  redis:
    image: redis:3.2

  postgres:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  bundle:
  pg_data:
  socket_io_node_modules:
  slackerboard_node_modules:
