version: "3"
services:
  nginx:
    links:
      - api
      - socket_io
    volumes:
      - ./slackerboard/dist:/var/slackerboard
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/prod/ssl.conf:/etc/nginx/ssl.conf
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
      - /emoji:/emoji
    ports:
      - 80:80
      - 443:443
      - 4200:4200

  slackerboard:
    build: slackerboard
    command: echo 'not running in production'
    volumes:
      - ./slackerboard:/usr/src/app
      - slackerboard_node_modules:/usr/src/app/node_modules

  api: &rails_prod_build
    environment:
      - PORT=5000
      - RAILS_ENV=production

  sidekiq:
    <<: *rails_prod_build
    command: sidekiq -C config/sidekiq.yml

  lurkerbot:
    <<: *rails_prod_build
    command: rake lurkerbot:start
