version: "3"
services:
  nginx:
    image: nginx
    links:
      - api
      - socket_io
    volumes:
      - ./slackerboard/dist:/var/slackerboard
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/prod/ssl.conf:/etc/nginx/ssl.conf
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt

    ports:
      - 80:80
      - 443:443
      - 4200:4200

  slackerboard:
    build: slackerboard
    command: echo 'not running in production'
    volumes:
      - ./slackerboard:/usr/src/app
      - slackerboard_node_modules:/usr/src/app/node_modules

  api: &rails_build
    build: api
    command: bundle exec rails s -p 5000 -b 0.0.0.0
    environment:
      - PORT=5000
      - RAILS_ENV=production
    env_file:
      - ./api/.env
    volumes:
      - ./api:/home/app/webapp
      - bundle:/usr/local/bundle
    links:
      - postgres
      - redis

  sidekiq:
    <<: *rails_build
    command: sidekiq -C config/sidekiq.yml

  lurkerbot:
    <<: *rails_build
    command: rake lurkerbot:start

  socket_io:
    build: socket_io
    command: npm start
    links:
      - redis
    volumes:
      - ./socket_io:/usr/src/app
      - socket_io_node_modules:/usr/src/app/node_modules

  redis:
    image: redis:3.2

  postgres:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  bundle:
  pg_data:
  socket_io_node_modules:
  slackerboard_node_modules:
