#!/bin/bash


# SETUP:
# git checkout --orphan gh-pages
# git reset
# git commit --allow-empty -m 'Initial commit'
# git checkout --force master
# git worktree add dist gh-pages

yarn run build

(
cd dist
echo slackerboard.charlottedevs.com > CNAME
git add --all
git commit -m "$(git log '--format=format:%H' master -1)"
git push origin gh-pages --force
)

