#!/bin/bash

set -e

if test -n "$(git status --porcelain)"
then
  echo 'dirty working tree. exiting...'
  exit 1
fi

source .env
./script/download-custom-emoji

if test -n "$(git status --porcelain)"
then
  echo 'new emoji found'
  git add .
  git commit -m 'add emoji'
  git push
  echo 'deploying...'
  script/deploy-gh-pages
else
  echo 'no new emoji'
fi

