module.exports = [
  {
    "id":1,
    "slack_handle":"coolguy",
    "real_name":"Real Name",
    "profile_image":"http://somewhere.com/jpg",
    "messages":[
      {
        "channel":"general",
        "slack_identifier":"1fd5q",
        "message_sent":124
      },
      {
        "channel":"random",
        "slack_identifier":"9gc81",
        "message_sent":394
      }
    ],
    "reactions":[
      {
        "emoji":"cat",
        "reactions_given":9
      },
      {
        "emoji":"dog",
        "reactions_given":51
      },
      {
        "emoji":"+1",
        "reactions_given":123
      }
    ]
}
]
