source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.4.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'

gem "interactor", "~> 3.0"
gem "sidekiq"
gem 'faraday'
gem 'jbuilder', '~> 2.5'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'rack-cors'
gem 'redis'
gem 'scenic'
gem 'slack-ruby-client'
gem 'celluloid-io', require: ['celluloid/current', 'celluloid/io']

group :development, :test do
  gem 'factory_bot_rails'
  gem 'guard-rspec'
  gem "rspec-rails"
  gem 'pry-rails'
  gem 'dotenv-rails'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
